sonar.projectKey=ha-flow-map
sonar.projectName=HA Flow Map
sonar.projectVersion=2026.8.0

sonar.sources=custom_components/ha_flow_map
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=tests/**,custom_components/ha_flow_map/frontend/**
sonar.exclusions=custom_components/ha_flow_map/frontend/**
sonar.qualitygate.wait=true
